name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 38.242.250.189

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: spearx/kaufland-game

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Deploy to swarm
      #   uses: sagebind/docker-swarm-deploy-action@v2
      #   with:
      #     remote_host: ssh://digital@vmi1347252.contaboserver.net
      #     ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      #     args: stack deploy --compose-file ~/home/digital/git/stack.yml kaufland-game:main

      # - name: Deploy to Docker swarm
      #   uses: wshihadeh/docker-deployment-action@v1
      #   with:
      #     remote_docker_host: digital@vmi1347252.contaboserver.net
      #     ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      #     deployment_mode: docker-swarm
      #     copy_stack_file: true
      #     deploy_path: ~/home/digital/git
      #     stack_file_name: stack.yaml
      #     keep_files: 5
      #     args: my_applicaion
      #     docker_prune: true

      # - name: Run Docker image on remote server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 38.242.250.189
      #     username: digital
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker stop kaufland-game || true
      #       docker rm kaufland-game || true
      #       docker system prune -a -f
      #       docker run -d -p 3000:3000 --name kaufland-game spearx/kaufland-game:main

      - name: Deploy Docker stack on remote server
        uses: appleboy/ssh-action@master
        with:
          host: 38.242.250.189
          username: digital
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker service rm registry || true
            docker stack rm stackdemo || true
            docker stack deploy --compose-file /home/digital/git/stack.yml kaufland-game-swarm
