name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: spearx/kaufland-game

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 38.242.250.189

      - name: Pull docker-compose.yml, game and CMS to server
        run: |
#          ssh digital@38.242.250.189 "rm /home/digital/git/docker-compose.yml"
          echo "Overwriting docker compose yml..."
          scp -o docker-compose.yml digital@38.242.250.189:/home/digital/git/
          echo "Overwriting game..."
          scp -o -r ./game digital@38.242.250.189:/home/digital/git/
#          echo "Overwriting cms..."
#          scp -o -r ./cms digital@38.242.250.189:/home/digital/git/

      - name: Remove Docker Compose stack
        run: |
          echo "Removing previous stack"
          ssh digital@38.242.250.189 "docker stack rm kaufland-stack"

      - name: Start new stack
        run: |
          echo "Starting new stack"
          ssh digital@38.242.250.189 "docker stack deploy -c /home/digital/git/docker-compose.yml kaufland-stack"



# PREVIOUS CODE
      # - name: Deploy to swarm
      #   uses: sagebind/docker-swarm-deploy-action@v2
      #   with:
      #     remote_host: ssh://digital@vmi1347252.contaboserver.net
      #     ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      #     args: stack deploy --compose-file ~/home/digital/git/stack.yml kaufland-game:main

      # - name: Deploy to Docker swarm
      #   uses: wshihadeh/docker-deployment-action@v1
      #   with:
      #     remote_docker_host: digital@vmi1347252.contaboserver.net
      #     ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      #     ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      #     deployment_mode: docker-swarm
      #     copy_stack_file: true
      #     deploy_path: ~/home/digital/git
      #     stack_file_name: stack.yaml
      #     keep_files: 5
      #     args: my_applicaion
      #     docker_prune: true

      # - name: Run Docker image on remote server
      #   env:
      #     SUPABASE_URL: ${{ secrets.NUXT_HOST }}
      #     SUPABASE_KEY: ${{ secrets.NUXT_PORT }}
      #     NUXT_SANITY_TOKEN: ${{ secrets.NUXT_PORT }}
      #
      #     SUPABASE_QUERY_URL: ${{ secrets.NUXT_PORT }}
      #     API_KEY: ${{ secrets.NUXT_PORT }}
      #     BEARER_TOKEN: ${{ secrets.NUXT_PORT }}
      #     BASE_URL: ${{ secrets.NUXT_PORT }}
      #
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 38.242.250.189
      #     username: digital
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker stop kaufland-game || true
      #       docker rm kaufland-game || true
      #       docker system prune -a -f
      #       docker run -v /home/digital/git/.env -d -p 3000:3000 --name kaufland-game spearx/kaufland-game:main

      # - name: Deploy Docker stack on remote server
      #   env:
      #     SUPABASE_URL: ${{ secrets.NUXT_HOST }}
      #     SUPABASE_KEY: ${{ secrets.NUXT_PORT }}
      #     NUXT_SANITY_TOKEN: ${{ secrets.NUXT_PORT }}
      #
      #     SUPABASE_QUERY_URL: ${{ secrets.NUXT_PORT }}
      #     API_KEY: ${{ secrets.NUXT_PORT }}
      #     BEARER_TOKEN: ${{ secrets.NUXT_PORT }}
      #     BASE_URL: ${{ secrets.NUXT_PORT }}
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 38.242.250.189
      #     username: digital
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       docker service rm kaufland-game-service || true
      #       docker pull spearx/kaufland-game:main
      #       docker swarm init
      #       docker service create --name kaufland-game-service --replicas 3 spearx/kaufland-game:main
