name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: spearx/kaufland-game:main
          build-args: |
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - uses: actions/checkout@v3
  #
  #     - name: Set up SSH
  #       uses: kielabokkie/ssh-key-and-known-hosts-action@v1
  #       with:
  #         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         ssh-host: 38.242.250.189
  #
  #     - name: Remove Docker Compose stack
  #       run: |
  #         echo "Removing previous stack"
  #         ssh digital@38.242.250.189 "docker system prune -a -f"
  #         ssh digital@38.242.250.189 "docker stack rm kaufland-stack"
  #
  #     - name: Start new stack
  #       run: |
  #         echo "Starting new stack"
  #         sleep 10  # Add a delay of 10 seconds
  #         ssh digital@38.242.250.189 "docker stack deploy -c /home/digital/git/docker-compose.yml kaufland-stack"

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 38.242.250.189

      - name: Remove Docker Compose stack
        run: |
          echo "Removing previous stack"
          ssh digital@38.242.250.189 "docker stack rm kaufland-stack"

      - name: Wait for old stack to be removed
        run: |
          echo "Waiting for old stack to be removed"
          while ssh digital@38.242.250.189 "docker stack ls | grep -q kaufland-stack"
          do
            echo "Old stack is still present, waiting..."
            sleep 5
          done

      - name: Docker system prune
        run: |
          echo "Pruning Docker system"
          ssh digital@38.242.250.189 "docker system prune -f"

      - name: Start new stack
        run: |
          echo "Starting new stack"
          ssh digital@38.242.250.189 "docker stack deploy -c /home/digital/git/docker-compose.yml kaufland-stack"
